# Generated by Django 6.1.1 on 2026-09-17 19:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft (hidden from visitors)'), ('published', 'Published (live on the website)')], default='draft', help_text="Only 'Published' items appear on the website. Use 'Draft' while you work.", max_length=12)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Set a future date and time to schedule publication.')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Edit these directly in the list view to reorder.')),
                ('author_name', models.CharField(help_text="e.g. 'Daniel R.' or full name.", max_length=80)),
                ('author_role', models.CharField(blank=True, help_text='e.g. Operations Manager', max_length=80)),
                ('company', models.CharField(blank=True, help_text="e.g. 'Bar group, Soho'", max_length=120)),
                ('quote', models.TextField(help_text='The review text, verbatim.', max_length=600)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Stars out of 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('source', models.CharField(choices=[('google', 'Google'), ('trustpilot', 'Trustpilot'), ('checkatrade', 'Checkatrade'), ('direct', 'Given directly to us')], default='google', help_text='Where the review was left. Shown as a small label.', max_length=12)),
                ('source_url', models.URLField(blank=True, help_text='Link to the original review, if any.')),
                ('date', models.DateField(help_text='When the review was left.')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on the homepage.')),
                ('area', models.ForeignKey(blank=True, help_text='Optional. Lets the area landing page show this review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='locations.servicearea')),
                ('service', models.ForeignKey(blank=True, help_text='Optional. Lets the service page show this review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='services.service')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['order', '-date'],
                'abstract': False,
            },
        ),
    ]
