# Generated by Django 6.1.1 on 2026-09-17 19:51

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Edit these directly in the list view to reorder.')),
                ('image', models.ImageField(help_text='Recommended: JPG or WebP, 1600 × 1000 px (16:10), under 300 KB.', upload_to='case-studies/gallery/', validators=[apps.core.validators.validate_image_upload_size])),
                ('alt_text', models.CharField(help_text='Describe the photo.', max_length=160)),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Gallery photo',
                'verbose_name_plural': 'Gallery photos',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft (hidden from visitors)'), ('published', 'Published (live on the website)')], default='draft', help_text="Only 'Published' items appear on the website. Use 'Draft' while you work.", max_length=12)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Set a future date and time to schedule publication.')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Edit these directly in the list view to reorder.')),
                ('meta_title', models.CharField(blank=True, help_text='Title shown in Google. Leave blank to use the page title. Max 70 characters; 50–60 is ideal.', max_length=70, verbose_name='Search result title')),
                ('meta_description', models.CharField(blank=True, help_text='Two sentences shown under the title in Google. Max 160 characters.', max_length=160, verbose_name='Search result description')),
                ('canonical_url', models.URLField(blank=True, help_text='Advanced. Only fill in if this page duplicates another page that should rank instead.', verbose_name='Canonical URL override')),
                ('og_image', models.ImageField(blank=True, help_text="Shown when this page is shared on LinkedIn/WhatsApp. Leave blank to use the page's main image or the site default. Recommended: JPG or PNG, exactly 1200 × 630 px, under 300 KB.", upload_to='og/', validators=[apps.core.validators.validate_image_upload_size], verbose_name='Social sharing image')),
                ('noindex', models.BooleanField(default=False, help_text='Tick to ask Google not to list this page. Use for thank-you pages only.', verbose_name='Hide from search engines')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(help_text="e.g. 'restaurants' becomes /sectors/restaurants/.", max_length=80, unique=True)),
                ('headline', models.CharField(blank=True, help_text='Heading on the sector page. Defaults to the name.', max_length=120)),
                ('intro', models.TextField(help_text="Why this sector's cooling needs are different.", max_length=800)),
                ('hero_image', models.ImageField(blank=True, help_text='Recommended: JPG or WebP, 1600 × 1000 px (16:10), under 300 KB.', upload_to='sectors/', validators=[apps.core.validators.validate_image_upload_size])),
                ('hero_image_alt', models.CharField(blank=True, max_length=160)),
                ('icon', models.CharField(choices=[('wrench', 'Wrench (repair)'), ('calendar-check', 'Calendar with tick (maintenance)'), ('plus-square', 'Plus in square (new installation)'), ('snowflake', 'Snowflake (refrigeration)'), ('wind', 'Airflow (air conditioning)'), ('bolt', 'Lightning bolt (emergency)'), ('shield-check', 'Shield with tick (compliance)'), ('clock', 'Clock (response time)'), ('phone', 'Phone'), ('map-pin', 'Map pin'), ('thermometer', 'Thermometer'), ('building', 'Building')], default='building', max_length=30)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft (hidden from visitors)'), ('published', 'Published (live on the website)')], default='draft', help_text="Only 'Published' items appear on the website. Use 'Draft' while you work.", max_length=12)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Set a future date and time to schedule publication.')),
                ('meta_title', models.CharField(blank=True, help_text='Title shown in Google. Leave blank to use the page title. Max 70 characters; 50–60 is ideal.', max_length=70, verbose_name='Search result title')),
                ('meta_description', models.CharField(blank=True, help_text='Two sentences shown under the title in Google. Max 160 characters.', max_length=160, verbose_name='Search result description')),
                ('canonical_url', models.URLField(blank=True, help_text='Advanced. Only fill in if this page duplicates another page that should rank instead.', verbose_name='Canonical URL override')),
                ('og_image', models.ImageField(blank=True, help_text="Shown when this page is shared on LinkedIn/WhatsApp. Leave blank to use the page's main image or the site default. Recommended: JPG or PNG, exactly 1200 × 630 px, under 300 KB.", upload_to='og/', validators=[apps.core.validators.validate_image_upload_size], verbose_name='Social sharing image')),
                ('noindex', models.BooleanField(default=False, help_text='Tick to ask Google not to list this page. Use for thank-you pages only.', verbose_name='Hide from search engines')),
                ('title', models.CharField(help_text="e.g. 'Walk-in freezer replacement for a Soho restaurant group'", max_length=140)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('client_name', models.CharField(help_text="Real client name. Tick 'Anonymise' below if you cannot name them publicly.", max_length=120)),
                ('client_anonymised', models.BooleanField(default=False, help_text="Shows the sector instead of the client name (e.g. 'A Mayfair hotel').", verbose_name='Anonymise client')),
                ('anonymised_label', models.CharField(blank=True, help_text="What to show instead of the client name, e.g. 'A Mayfair boutique hotel'.", max_length=120)),
                ('scale_metric', models.CharField(blank=True, help_text="One measurable fact, e.g. '800 sqm venue' or '14 display cabinets'.", max_length=80)),
                ('summary', models.CharField(help_text='One sentence for cards and Google. Max 200 characters.', max_length=200)),
                ('challenge', models.TextField(help_text='What was wrong or needed? Plain text paragraphs.')),
                ('solution', models.TextField(help_text='What you installed or fixed, and how.')),
                ('result', models.TextField(help_text='Outcome in numbers where possible: energy saved, downtime avoided, temps held.', verbose_name='Result / return on investment')),
                ('hero_image', models.ImageField(blank=True, help_text='Recommended: JPG or WebP, 1600 × 1000 px (16:10), under 300 KB.', upload_to='case-studies/', validators=[apps.core.validators.validate_image_upload_size])),
                ('hero_image_alt', models.CharField(blank=True, max_length=160)),
                ('completed_on', models.DateField(blank=True, help_text='When the job finished.', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text="Show on the homepage 'Recent work' section.")),
                ('area', models.ForeignKey(blank=True, help_text='Borough or town. Lets the area landing page show this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='locations.servicearea')),
            ],
            options={
                'verbose_name': 'Case study',
                'verbose_name_plural': 'Case studies',
                'ordering': ['-is_featured', '-completed_on', '-published_at'],
            },
        ),
    ]
