# Generated by Django 6.1.1 on 2026-09-17 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('services', '0001_initial'),
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='services',
            field=models.ManyToManyField(help_text='Services delivered on this project.', related_name='case_studies', to='services.service'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='testimonial',
            field=models.ForeignKey(blank=True, help_text='Optional quote from this client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='testimonials.testimonial'),
        ),
        migrations.AddField(
            model_name='casestudyimage',
            name='case_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.casestudy'),
        ),
        migrations.AddField(
            model_name='sector',
            name='key_services',
            field=models.ManyToManyField(blank=True, help_text='Services most relevant to this sector, shown as cards.', related_name='sectors', to='services.service'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='sector',
            field=models.ForeignKey(help_text="Client's sector.", on_delete=django.db.models.deletion.PROTECT, related_name='case_studies', to='projects.sector'),
        ),
    ]
