# Generated by Django 6.1.1 on 2026-09-17 19:51

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pages', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft (hidden from visitors)'), ('published', 'Published (live on the website)')], default='draft', help_text="Only 'Published' items appear on the website. Use 'Draft' while you work.", max_length=12)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Set a future date and time to schedule publication.')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Edit these directly in the list view to reorder.')),
                ('meta_title', models.CharField(blank=True, help_text='Title shown in Google. Leave blank to use the page title. Max 70 characters; 50–60 is ideal.', max_length=70, verbose_name='Search result title')),
                ('meta_description', models.CharField(blank=True, help_text='Two sentences shown under the title in Google. Max 160 characters.', max_length=160, verbose_name='Search result description')),
                ('canonical_url', models.URLField(blank=True, help_text='Advanced. Only fill in if this page duplicates another page that should rank instead.', verbose_name='Canonical URL override')),
                ('og_image', models.ImageField(blank=True, help_text="Shown when this page is shared on LinkedIn/WhatsApp. Leave blank to use the page's main image or the site default. Recommended: JPG or PNG, exactly 1200 × 630 px, under 300 KB.", upload_to='og/', validators=[apps.core.validators.validate_image_upload_size], verbose_name='Social sharing image')),
                ('noindex', models.BooleanField(default=False, help_text='Tick to ask Google not to list this page. Use for thank-you pages only.', verbose_name='Hide from search engines')),
                ('name', models.CharField(help_text='e.g. Commercial Refrigeration', max_length=80)),
                ('slug', models.SlugField(help_text="Web address, e.g. 'commercial-refrigeration' becomes /commercial-refrigeration/. Changing this breaks existing links.", max_length=80, unique=True)),
                ('headline', models.CharField(blank=True, help_text='Optional larger heading on the hub page. Defaults to the name.', max_length=120)),
                ('intro', models.TextField(help_text='Two or three sentences at the top of the hub page.', max_length=600)),
                ('hero_image', models.ImageField(blank=True, help_text='Recommended: JPG or WebP, 1600 × 1000 px (16:10), under 300 KB.', upload_to='services/', validators=[apps.core.validators.validate_image_upload_size])),
                ('hero_image_alt', models.CharField(blank=True, max_length=160)),
                ('icon', models.CharField(choices=[('wrench', 'Wrench (repair)'), ('calendar-check', 'Calendar with tick (maintenance)'), ('plus-square', 'Plus in square (new installation)'), ('snowflake', 'Snowflake (refrigeration)'), ('wind', 'Airflow (air conditioning)'), ('bolt', 'Lightning bolt (emergency)'), ('shield-check', 'Shield with tick (compliance)'), ('clock', 'Clock (response time)'), ('phone', 'Phone'), ('map-pin', 'Map pin'), ('thermometer', 'Thermometer'), ('building', 'Building')], default='snowflake', max_length=30)),
                ('audience', models.CharField(blank=True, default='Contract buyers comparing suppliers; emergency callers land on the emergency page instead.', help_text='Internal note: who is this hub for?', max_length=120)),
            ],
            options={
                'verbose_name': 'Service category',
                'verbose_name_plural': 'Service categories',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft (hidden from visitors)'), ('published', 'Published (live on the website)')], default='draft', help_text="Only 'Published' items appear on the website. Use 'Draft' while you work.", max_length=12)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Set a future date and time to schedule publication.')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Edit these directly in the list view to reorder.')),
                ('meta_title', models.CharField(blank=True, help_text='Title shown in Google. Leave blank to use the page title. Max 70 characters; 50–60 is ideal.', max_length=70, verbose_name='Search result title')),
                ('meta_description', models.CharField(blank=True, help_text='Two sentences shown under the title in Google. Max 160 characters.', max_length=160, verbose_name='Search result description')),
                ('canonical_url', models.URLField(blank=True, help_text='Advanced. Only fill in if this page duplicates another page that should rank instead.', verbose_name='Canonical URL override')),
                ('og_image', models.ImageField(blank=True, help_text="Shown when this page is shared on LinkedIn/WhatsApp. Leave blank to use the page's main image or the site default. Recommended: JPG or PNG, exactly 1200 × 630 px, under 300 KB.", upload_to='og/', validators=[apps.core.validators.validate_image_upload_size], verbose_name='Social sharing image')),
                ('noindex', models.BooleanField(default=False, help_text='Tick to ask Google not to list this page. Use for thank-you pages only.', verbose_name='Hide from search engines')),
                ('name', models.CharField(help_text='e.g. Walk-In Cold Rooms', max_length=100)),
                ('slug', models.SlugField(help_text="Web address within the category, e.g. 'walk-in-cold-rooms' becomes /commercial-refrigeration/walk-in-cold-rooms/.", max_length=100)),
                ('short_summary', models.CharField(help_text='One sentence shown on cards and in Google. Max 200 characters.', max_length=200)),
                ('intro', models.TextField(blank=True, help_text='Opening paragraph on the service page.', max_length=800)),
                ('hero_image', models.ImageField(blank=True, help_text='Recommended: JPG or WebP, 1600 × 1000 px (16:10), under 300 KB.', upload_to='services/', validators=[apps.core.validators.validate_image_upload_size])),
                ('hero_image_alt', models.CharField(blank=True, max_length=160)),
                ('icon', models.CharField(choices=[('wrench', 'Wrench (repair)'), ('calendar-check', 'Calendar with tick (maintenance)'), ('plus-square', 'Plus in square (new installation)'), ('snowflake', 'Snowflake (refrigeration)'), ('wind', 'Airflow (air conditioning)'), ('bolt', 'Lightning bolt (emergency)'), ('shield-check', 'Shield with tick (compliance)'), ('clock', 'Clock (response time)'), ('phone', 'Phone'), ('map-pin', 'Map pin'), ('thermometer', 'Thermometer'), ('building', 'Building')], default='snowflake', max_length=30)),
                ('typical_response_time', models.CharField(blank=True, help_text="e.g. 'Same day' or 'Within 2 hours, 24/7'. Shown as a fact chip.", max_length=60)),
                ('price_from_note', models.CharField(blank=True, help_text="e.g. 'PPM contracts from £45 per unit per visit'. Leave blank to hide.", max_length=120)),
                ('is_featured', models.BooleanField(default=False, help_text="Show this service in the homepage 'What we do' grid.")),
                ('is_emergency', models.BooleanField(default=False, help_text='Tick for emergency services so cards use the orange call button.')),
                ('brands', models.ManyToManyField(blank=True, help_text='Manufacturers you install or maintain for this service.', related_name='services', to='core.brandserviced')),
                ('related_case_studies', models.ManyToManyField(blank=True, help_text='Proof: pick up to three relevant case studies.', related_name='featured_on_services', to='projects.casestudy')),
                ('related_services', models.ManyToManyField(blank=True, help_text="Shown as 'You may also need' at the bottom of the page.", to='services.service')),
                ('category', models.ForeignKey(help_text='Which hub this service is listed under.', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Edit these directly in the list view to reorder.')),
                ('block_type', models.CharField(choices=[('rich_text', 'Text'), ('image_text', 'Image + text side by side'), ('stat_row', 'Row of statistics'), ('faq', 'FAQ accordion'), ('cta_band', 'Call-to-action band'), ('logo_strip', 'Logo strip (accreditations, brands, clients)'), ('video', 'Video band'), ('gallery', 'Image gallery'), ('feature_grid', 'Feature grid (2 or 3 columns)')], default='rich_text', help_text='What kind of section this is. Fill in only the fields that apply.', max_length=20)),
                ('heading', models.CharField(blank=True, help_text='Section heading. Leave blank for none.', max_length=120)),
                ('body', models.TextField(blank=True, help_text="Main text. Blank line = new paragraph. Start a line with '- ' for a bullet, '## ' for a sub-heading, and wrap words in **double stars** for bold.")),
                ('items', models.TextField(blank=True, help_text='One item per line for statistics, FAQs and feature grids. Format: Title :: Body :: Link (Body and Link are optional). For FAQs use: Question? :: Answer.')),
                ('image', models.ImageField(blank=True, help_text="Used by 'Image + text'. Recommended: JPG or WebP, 1600 × 1000 px (16:10), under 300 KB.", upload_to='blocks/', validators=[apps.core.validators.validate_image_upload_size])),
                ('image_alt', models.CharField(blank=True, max_length=160)),
                ('image_position', models.CharField(choices=[('left', 'Image on the left'), ('right', 'Image on the right')], default='left', max_length=6)),
                ('cta_label', models.CharField(blank=True, help_text="Button text, e.g. 'Request a quote'.", max_length=40)),
                ('cta_url', models.CharField(blank=True, help_text='Button link, e.g. /quote/ or tel:+44...', max_length=200)),
                ('cta_is_phone', models.BooleanField(default=False, help_text='Tick to make the button dial the emergency line instead of using the link.')),
                ('video_embed_url', models.URLField(blank=True, help_text='YouTube/Vimeo embed URL for a video band, e.g. https://www.youtube-nocookie.com/embed/VIDEO_ID')),
                ('logo_source', models.CharField(choices=[('badges', 'Accreditation badges'), ('brands', 'Brands we service'), ('clients', 'Client logos')], default='badges', help_text="Used by 'Logo strip'.", max_length=10)),
                ('columns', models.PositiveSmallIntegerField(choices=[(2, '2 columns'), (3, '3 columns'), (4, '4 columns')], default=3, help_text="Used by 'Feature grid' and 'Row of statistics'.")),
                ('background', models.CharField(choices=[('white', 'White'), ('ice', 'Ice tint (light blue-grey)'), ('navy', 'Navy (dark)')], default='white', max_length=6)),
                ('anchor_id', models.SlugField(blank=True, help_text='Optional. Lets you link straight to this section with #your-anchor.', max_length=40)),
                ('gallery_images', models.ManyToManyField(blank=True, help_text="Used by 'Image gallery'. Add images in the Media library first.", to='pages.mediaasset')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='services.service')),
            ],
            options={
                'verbose_name': 'Content block',
                'verbose_name_plural': 'Content blocks',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Edit these directly in the list view to reorder.')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(help_text='Plain text. Google shows this directly in search results.')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.service')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Edit these directly in the list view to reorder.')),
                ('label', models.CharField(help_text='e.g. Refrigerants', max_length=60)),
                ('value', models.CharField(help_text='e.g. R290, R32, R448A, R449A', max_length=160)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='services.service')),
            ],
            options={
                'verbose_name': 'Technical specification',
                'verbose_name_plural': 'Technical specifications',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='unique_service_slug_per_category'),
        ),
    ]
