# Generated by Django 6.1.1 on 2026-09-26 13:18

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='intro',
            field=models.TextField(help_text='Two or three sentences at the top of the hub page.', max_length=900),
        ),
        migrations.CreateModel(
            name='ServiceCategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Edit these directly in the list view to reorder.')),
                ('image', models.ImageField(help_text='Recommended: JPG or WebP, 1600 × 1000 px (16:10), under 300 KB.', upload_to='services/gallery/', validators=[apps.core.validators.validate_image_upload_size])),
                ('alt', models.CharField(blank=True, help_text='Alt text for accessibility.', max_length=160)),
                ('category', models.ForeignKey(help_text='The service category this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Category gallery image',
                'verbose_name_plural': 'Category gallery images',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
