# Generated by Django 6.1.1 on 2026-09-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_servicecategory_intro_servicecategoryimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="gallery_content",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
