# Generated by Django 6.1.1 on 2026-09-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='icon',
            field=models.CharField(blank=True, choices=[('wrench', 'Wrench (repair)'), ('calendar-check', 'Calendar with tick (maintenance)'), ('plus-square', 'Plus in square (new installation)'), ('snowflake', 'Snowflake (refrigeration)'), ('wind', 'Airflow (air conditioning)'), ('bolt', 'Lightning bolt (emergency)'), ('shield-check', 'Shield with tick (compliance)'), ('clock', 'Clock (response time)'), ('phone', 'Phone'), ('map-pin', 'Map pin'), ('thermometer', 'Thermometer'), ('building', 'Building')], help_text='Optional icon shown beside the label in the menu.', max_length=32),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='subtitle',
            field=models.CharField(blank=True, help_text="Optional line shown under the label, e.g. 'Same-day repairs'. Three or four words at most; it is hidden on narrow screens and once the header shrinks on scroll.", max_length=60, verbose_name='Caption'),
        ),
    ]
