# Generated by Django 6.1.1 on 2026-09-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_navigationitem_icon_navigationitem_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="home_services_intro",
            field=models.CharField(
                blank=True,
                default="Design, installation, planned maintenance and repair for commercial cooling — one contractor, one point of contact, one set of compliance records.",
                help_text="One sentence under the heading.",
                max_length=540,
            ),
        ),
    ]
