# Generated by Django 6.1.1 on 2026-09-17 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Edit these directly in the list view to reorder.')),
                ('group', models.CharField(choices=[('enquiry_type', 'Contact form: enquiry type'), ('emergency_issue', 'Emergency form: what has failed'), ('building_type', 'Quote wizard: building type'), ('floor_area', 'Quote wizard: floor area band'), ('system_type', 'Quote wizard: system type'), ('timeline', 'Quote wizard: timeline'), ('budget_band', 'Quote wizard: budget band')], db_index=True, help_text='Which form field this option belongs to.', max_length=20)),
                ('label', models.CharField(help_text='What the visitor sees.', max_length=80)),
                ('value', models.SlugField(help_text="Short internal code, e.g. 'restaurant'. Letters, numbers and hyphens.", max_length=60)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide from the form.')),
            ],
            options={
                'verbose_name': 'Form dropdown option',
                'verbose_name_plural': 'Form dropdown options',
                'ordering': ['group', 'order', 'label'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('group', 'value'), name='unique_choice_per_group')],
            },
        ),
        migrations.CreateModel(
            name='EmergencyCallout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', help_text='Move the lead through the pipeline as you work it.', max_length=12)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source_url', models.CharField(blank=True, editable=False, help_text='Page the form was sent from.', max_length=300)),
                ('referrer', models.CharField(blank=True, editable=False, max_length=300)),
                ('user_agent', models.CharField(blank=True, editable=False, max_length=300)),
                ('consent', models.BooleanField(default=False, help_text='Visitor agreed to be contacted about their enquiry.')),
                ('notified_at', models.DateTimeField(blank=True, editable=False, help_text='When the notification email was sent.', null=True)),
                ('postcode', models.CharField(blank=True, max_length=12)),
                ('details', models.CharField(blank=True, max_length=300)),
                ('called_back_at', models.DateTimeField(blank=True, help_text='Record when an engineer rang the customer back.', null=True)),
                ('issue', models.ForeignKey(blank=True, limit_choices_to={'group': 'emergency_issue'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.formfieldchoice')),
            ],
            options={
                'verbose_name': 'Emergency callback',
                'verbose_name_plural': 'Emergency callbacks',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', help_text='Move the lead through the pipeline as you work it.', max_length=12)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source_url', models.CharField(blank=True, editable=False, help_text='Page the form was sent from.', max_length=300)),
                ('referrer', models.CharField(blank=True, editable=False, max_length=300)),
                ('user_agent', models.CharField(blank=True, editable=False, max_length=300)),
                ('consent', models.BooleanField(default=False, help_text='Visitor agreed to be contacted about their enquiry.')),
                ('notified_at', models.DateTimeField(blank=True, editable=False, help_text='When the notification email was sent.', null=True)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('enquiry_type', models.ForeignKey(blank=True, limit_choices_to={'group': 'enquiry_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.formfieldchoice')),
            ],
            options={
                'verbose_name': 'Contact enquiry',
                'verbose_name_plural': 'Contact enquiries',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('note', models.TextField(help_text='Internal only — never shown to the customer.')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Internal note',
                'verbose_name_plural': 'Internal notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='leads_leadn_content_a22318_idx')],
            },
        ),
    ]
