# Generated by Django 6.1.1 on 2026-09-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencycallout",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="formfieldchoice",
            name="group",
            field=models.CharField(
                choices=[
                    ("enquiry_type", ""),
                    ("emergency_issue", "Emergency"),
                    ("building_type", "Quote wizard: building type"),
                    ("floor_area", "Quote wizard: floor area band"),
                    ("system_type", "Quote wizard: system type"),
                    ("timeline", "Quote wizard: timeline"),
                    ("budget_band", "Quote wizard: budget band"),
                ],
                db_index=True,
                help_text="Which form field this option belongs to.",
                max_length=20,
            ),
        ),
    ]
