# Generated by Django 6.1.1 on 2026-09-23 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_alter_emergencycallout_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("quoted", "Quoted"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        db_index=True,
                        default="new",
                        help_text="Move the lead through the pipeline as you work it.",
                        max_length=12,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "source_url",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Page the form was sent from.",
                        max_length=300,
                    ),
                ),
                ("referrer", models.CharField(blank=True, editable=False, max_length=300)),
                ("user_agent", models.CharField(blank=True, editable=False, max_length=300)),
                (
                    "consent",
                    models.BooleanField(
                        default=False,
                        help_text="Visitor agreed to be contacted about their enquiry.",
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="When the notification email was sent.",
                        null=True,
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=120)),
                ("message", models.TextField()),
                ("postcode", models.CharField(max_length=15)),
                (
                    "enquiry_type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"group": "enquiry_type"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="leads.formfieldchoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request enquiry",
                "verbose_name_plural": "Request enquiries",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
