# Generated by Django 6.1.1 on 2026-09-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_requestenquiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactenquiry",
            name="consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="emergencycallout",
            name="consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="requestenquiry",
            name="consent",
            field=models.BooleanField(default=False),
        ),
    ]
