# Generated by Django 6.1.1 on 2026-10-05 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0008_alter_repairrequest_equipment_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactenquiry",
            name="equipment_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"group": "equipment_type"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="leads.formfieldchoice",
            ),
        ),
        migrations.AlterField(
            model_name="formfieldchoice",
            name="group",
            field=models.CharField(
                choices=[
                    ("enquiry_type", ""),
                    ("emergency_issue", "Emergency"),
                    ("equipment_type", "Equipment Type"),
                    ("building_type", "Quote wizard: building type"),
                    ("floor_area", "Quote wizard: floor area band"),
                    ("system_type", "Quote wizard: system type"),
                    ("timeline", "Quote wizard: timeline"),
                    ("budget_band", "Quote wizard: budget band"),
                ],
                db_index=True,
                help_text="Which form field this option belongs to.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="repairrequest",
            name="equipment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WALK_IN", "Walk-In Freezer/Cooler"),
                    ("FREESTANDING", "Freestanding Refrigerator"),
                    ("SPLIT_SYSTEM", "Central Split System (A/C & Furnace)"),
                    ("ROOFTOP", "Rooftop Package Unit"),
                    ("ICE_MACHINE", "Commercial Ice Machine"),
                    ("REACH_IN", "Reach-In Refrigerator"),
                    ("CENTRAL_AC", "Central AC / Heat Pump"),
                    ("MINI_SPLIT", "Ductless Mini-Split"),
                    ("OTHER", "Other Equipment"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
