# Generated by Django 6.1.1 on 2026-10-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0009_contactenquiry_equipment_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RequestEnquiry",
        ),
    ]
