# Generated by Django 6.1.1 on 2026-10-07 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0010_delete_requestenquiry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmergencyCallout",
        ),
    ]
