# Generated by Django 6.1.1 on 2026-09-17 19:51

import apps.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft (hidden from visitors)'), ('published', 'Published (live on the website)')], default='draft', help_text="Only 'Published' items appear on the website. Use 'Draft' while you work.", max_length=12)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Set a future date and time to schedule publication.')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Edit these directly in the list view to reorder.')),
                ('meta_title', models.CharField(blank=True, help_text='Title shown in Google. Leave blank to use the page title. Max 70 characters; 50–60 is ideal.', max_length=70, verbose_name='Search result title')),
                ('meta_description', models.CharField(blank=True, help_text='Two sentences shown under the title in Google. Max 160 characters.', max_length=160, verbose_name='Search result description')),
                ('canonical_url', models.URLField(blank=True, help_text='Advanced. Only fill in if this page duplicates another page that should rank instead.', verbose_name='Canonical URL override')),
                ('og_image', models.ImageField(blank=True, help_text="Shown when this page is shared on LinkedIn/WhatsApp. Leave blank to use the page's main image or the site default. Recommended: JPG or PNG, exactly 1200 × 630 px, under 300 KB.", upload_to='og/', validators=[apps.core.validators.validate_image_upload_size], verbose_name='Social sharing image')),
                ('noindex', models.BooleanField(default=False, help_text='Tick to ask Google not to list this page. Use for thank-you pages only.', verbose_name='Hide from search engines')),
                ('name', models.CharField(help_text='e.g. Canary Wharf, Westminster, Reading', max_length=80)),
                ('slug', models.SlugField(help_text="Web address, e.g. 'canary-wharf' becomes /areas/air-conditioning-refrigeration-canary-wharf/.", max_length=100, unique=True)),
                ('region', models.CharField(choices=[('central', 'Central London'), ('east', 'East London'), ('north', 'North London'), ('south', 'South London'), ('west', 'West London'), ('greater', 'Greater London'), ('berkshire', 'Berkshire'), ('other', 'Other')], default='central', help_text="Groups the area on the 'Areas we cover' page.", max_length=12)),
                ('custom_h1', models.CharField(blank=True, help_text="Leave blank for 'Commercial refrigeration & air conditioning in <Name>'.", max_length=120, verbose_name='Custom page heading')),
                ('intro', models.TextField(help_text='Two or three paragraphs specific to this area: typical clients, local landmarks, travel time from base.', max_length=1200)),
                ('postcode_prefixes', models.CharField(blank=True, help_text="Comma-separated, e.g. E14, E1W. Shown as 'Covering E14, E1W'.", max_length=120)),
                ('typical_response_time', models.CharField(blank=True, help_text="e.g. 'Under 60 minutes'. Leave blank to use the site-wide promise.", max_length=60)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('hero_image', models.ImageField(blank=True, help_text='Recommended: JPG or WebP, 1600 × 1000 px (16:10), under 300 KB.', upload_to='areas/', validators=[apps.core.validators.validate_image_upload_size])),
                ('hero_image_alt', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'Service area',
                'verbose_name_plural': 'Service areas',
                'ordering': ['region', 'order', 'name'],
                'abstract': False,
            },
        ),
    ]
