# Generated by Django 6.1.1 on 2026-09-17 19:51

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Internal name so you can find it later.', max_length=120)),
                ('image', models.ImageField(help_text='Recommended: JPG or WebP, 1600 × 1000 px (16:10), under 300 KB.', upload_to='library/', validators=[apps.core.validators.validate_image_upload_size])),
                ('alt_text', models.CharField(help_text='Describe the image for screen readers and Google.', max_length=160)),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Media library image',
                'verbose_name_plural': 'Media library',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft (hidden from visitors)'), ('published', 'Published (live on the website)')], default='draft', help_text="Only 'Published' items appear on the website. Use 'Draft' while you work.", max_length=12)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Set a future date and time to schedule publication.')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Edit these directly in the list view to reorder.')),
                ('meta_title', models.CharField(blank=True, help_text='Title shown in Google. Leave blank to use the page title. Max 70 characters; 50–60 is ideal.', max_length=70, verbose_name='Search result title')),
                ('meta_description', models.CharField(blank=True, help_text='Two sentences shown under the title in Google. Max 160 characters.', max_length=160, verbose_name='Search result description')),
                ('canonical_url', models.URLField(blank=True, help_text='Advanced. Only fill in if this page duplicates another page that should rank instead.', verbose_name='Canonical URL override')),
                ('og_image', models.ImageField(blank=True, help_text="Shown when this page is shared on LinkedIn/WhatsApp. Leave blank to use the page's main image or the site default. Recommended: JPG or PNG, exactly 1200 × 630 px, under 300 KB.", upload_to='og/', validators=[apps.core.validators.validate_image_upload_size], verbose_name='Social sharing image')),
                ('noindex', models.BooleanField(default=False, help_text='Tick to ask Google not to list this page. Use for thank-you pages only.', verbose_name='Hide from search engines')),
                ('title', models.CharField(help_text='Page heading (the H1).', max_length=120)),
                ('slug', models.SlugField(help_text="Part of the web address, e.g. 'about' becomes /about/. Lowercase, hyphens. Special slugs 'services', 'sectors', 'case-studies', 'areas', 'contact' and 'emergency-callout' control the heading and intro of those built-in pages.", max_length=120, unique=True)),
                ('template', models.CharField(choices=[('standard', 'Standard (hero image, full-width blocks)'), ('narrow', 'Narrow reading column (legal pages, statements)'), ('landing', 'Landing page (no side padding, CTA-heavy)')], default='standard', help_text='Overall layout of the page.', max_length=20)),
                ('intro', models.TextField(blank=True, help_text='One or two sentences under the heading. Also used as the Google description if none is set.', max_length=400)),
                ('hero_image', models.ImageField(blank=True, help_text='Optional banner image. Recommended: JPG or WebP, 1600 × 1000 px (16:10), under 300 KB.', upload_to='pages/', validators=[apps.core.validators.validate_image_upload_size])),
                ('hero_image_alt', models.CharField(blank=True, max_length=160)),
                ('show_contact_cta', models.BooleanField(default=True, help_text="Show the standard 'Talk to an engineer' band at the bottom.")),
                ('audience_note', models.CharField(blank=True, help_text='Internal only: who is this page for? (Emergency caller / Contract buyer)', max_length=120)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Edit these directly in the list view to reorder.')),
                ('block_type', models.CharField(choices=[('rich_text', 'Text'), ('image_text', 'Image + text side by side'), ('stat_row', 'Row of statistics'), ('faq', 'FAQ accordion'), ('cta_band', 'Call-to-action band'), ('logo_strip', 'Logo strip (accreditations, brands, clients)'), ('video', 'Video band'), ('gallery', 'Image gallery'), ('feature_grid', 'Feature grid (2 or 3 columns)')], default='rich_text', help_text='What kind of section this is. Fill in only the fields that apply.', max_length=20)),
                ('heading', models.CharField(blank=True, help_text='Section heading. Leave blank for none.', max_length=120)),
                ('body', models.TextField(blank=True, help_text="Main text. Blank line = new paragraph. Start a line with '- ' for a bullet, '## ' for a sub-heading, and wrap words in **double stars** for bold.")),
                ('items', models.TextField(blank=True, help_text='One item per line for statistics, FAQs and feature grids. Format: Title :: Body :: Link (Body and Link are optional). For FAQs use: Question? :: Answer.')),
                ('image', models.ImageField(blank=True, help_text="Used by 'Image + text'. Recommended: JPG or WebP, 1600 × 1000 px (16:10), under 300 KB.", upload_to='blocks/', validators=[apps.core.validators.validate_image_upload_size])),
                ('image_alt', models.CharField(blank=True, max_length=160)),
                ('image_position', models.CharField(choices=[('left', 'Image on the left'), ('right', 'Image on the right')], default='left', max_length=6)),
                ('cta_label', models.CharField(blank=True, help_text="Button text, e.g. 'Request a quote'.", max_length=40)),
                ('cta_url', models.CharField(blank=True, help_text='Button link, e.g. /quote/ or tel:+44...', max_length=200)),
                ('cta_is_phone', models.BooleanField(default=False, help_text='Tick to make the button dial the emergency line instead of using the link.')),
                ('video_embed_url', models.URLField(blank=True, help_text='YouTube/Vimeo embed URL for a video band, e.g. https://www.youtube-nocookie.com/embed/VIDEO_ID')),
                ('logo_source', models.CharField(choices=[('badges', 'Accreditation badges'), ('brands', 'Brands we service'), ('clients', 'Client logos')], default='badges', help_text="Used by 'Logo strip'.", max_length=10)),
                ('columns', models.PositiveSmallIntegerField(choices=[(2, '2 columns'), (3, '3 columns'), (4, '4 columns')], default=3, help_text="Used by 'Feature grid' and 'Row of statistics'.")),
                ('background', models.CharField(choices=[('white', 'White'), ('ice', 'Ice tint (light blue-grey)'), ('navy', 'Navy (dark)')], default='white', max_length=6)),
                ('anchor_id', models.SlugField(blank=True, help_text='Optional. Lets you link straight to this section with #your-anchor.', max_length=40)),
                ('gallery_images', models.ManyToManyField(blank=True, help_text="Used by 'Image gallery'. Add images in the Media library first.", to='pages.mediaasset')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='pages.page')),
            ],
            options={
                'verbose_name': 'Content block',
                'verbose_name_plural': 'Content blocks',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
